services:
  db:
    image: mongo
    restart: always
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
    networks:
      - api-network

  api:
    build:
      context: .
    container_name: api
    ports:
      - '9000:8888'
    command: python3 -u main.py
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app
    environment:
      MONGO_URI: mongodb://admin:admin@db:27017
    networks:
      - api-network

networks:
  api-network:


volumes:
  mongo-data:
