services:
  db:
    build:
      context: ./db
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - ./db/transactions.agz:/data/transactions.agz

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017
